### ISSUE TITLE
Broken link to docs

### ISSUE THREAD

**Issue by mandeep** [ogham/rust-locale#21]
The link to the documentation website seems to be broken.

**Comment by jan-hudec** [comment]
The released version is pretty useless anyway. There is a prototype of rewrite on the next branch, but I need to get some time to finish it. Then I'll have to set up generating the documentation to somewhere (I've seen some central documentation site for rust, but have not yet looked if I could use it and what it takes).

**Comment by jan-hudec** [comment]
Fixed in 9acaf6987a97f8ffcda0e3ce6e8770e7a01ece09
