### ISSUE TITLE
Publishing new minor version

### ISSUE THREAD

**Issue by petrochenkov** [ogham/rust-locale#24]
Hi.
https://github.com/rust-lang/rust/pull/42136 is going to turn some old compatibility warnings in `rustc` into hard errors.
`crates.io` testing discovered that published version of this crate is affected by one of those errors (private enum variants are reexported publicly).
The current master is building successfully with https://github.com/rust-lang/rust/pull/42136, could you push it on crates.io as `locale-0.2.2`?

**Comment by jan-hudec** [comment]
Ok. Not that the library would be of much use in that state, but will do. New version that should be actually useful is (unfortunately rather slowly) cooking.

**Comment by petrochenkov** [comment]
Thanks!
Even if the library isn't used much, it helped with compiler's regression testing.
