### ISSUE TITLE
The final ARM broken crate

### ISSUE THREAD

**Issue by MagaTailor** [ogham/rust-locale#6]
More of the [same](https://github.com/rust-lang/rust/issues/29867):

``` rust
Compiling locale v0.1.8
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:19:41: 19:44 error: mismatched types:
 expected `*const u8`,
    found `*const i8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:19     let cres: &'a CStr = CStr::from_ptr(ptr);
                                                                                                                                           ^~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:19:41: 19:44 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:36:34: 36:37 error: mismatched types:
 expected `*const u8`,
    found `*const i8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:36         let len = CStr::from_ptr(ptr).to_bytes_with_nul().len();
                                                                                                                                    ^~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:36:34: 36:37 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:73:48: 73:51 error: mismatched types:
 expected `*const u8`,
    found `*const i8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:73         String::from_utf8_lossy(CStr::from_ptr(ptr).to_bytes())
                                                                                                                                                  ^~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/langinfo.rs:73:48: 73:51 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:25:61: 25:74 error: mismatched types:
 expected `*const i8`,
    found `*const u8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:25         let res = unsafe { ffi::newlocale(ffi::LC_ALL_MASK, cloc.as_ptr(), ::std::ptr::null_mut()) };
                                                                                                                                                          ^~~~~~~~~~~~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:25:61: 25:74 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:40:49: 40:62 error: mismatched types:
 expected `*const i8`,
    found `*const u8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:40         let res = unsafe { ffi::newlocale(mask, cloc.as_ptr(), from.c_locale) };
                                                                                                                                              ^~~~~~~~~~~~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:40:49: 40:62 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:61:49: 61:52 error: mismatched types:
 expected `*const u8`,
    found `*const i8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:61             let cres: &'a CStr = CStr::from_ptr(ptr);
                                                                                                                                              ^~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:61:49: 61:52 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:102:44: 102:56 error: mismatched types:
 expected `*const i8`,
    found `*const u8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:102         let res = unsafe { ffi::iconv_open(cto.as_ptr(), cfrom.as_ptr()) };
                                                                                                                                          ^~~~~~~~~~~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:102:44: 102:56 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:102:58: 102:72 error: mismatched types:
 expected `*const i8`,
    found `*const u8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:102         let res = unsafe { ffi::iconv_open(cto.as_ptr(), cfrom.as_ptr()) };
                                                                                                                                                        ^~~~~~~~~~~~~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:102:58: 102:72 help: run `rustc --explain E0308` to see a detailed explanation
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:182:25: 182:87 error: mismatched types:
 expected `*const u8`,
    found `*const i8` [E0308]
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:182                         ffi::nl_langinfo_l(codeset as ::libc::c_uint, locale.c_locale)).to_bytes())
                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/odroid/.cargo/registry/src/github.com-48ad6e4054423464/locale-0.1.8/src/linux/mod.rs:182:25: 182:87 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 9 previous errors
Could not compile `locale`.
```

Rustc nightly `1.8` (or rather >= 1.6) is affected whereas `1.5` is fine.

**Comment by jan-hudec** [comment]
@petevine, can you try the latest version from git? It seems this should be fixed by #5.

@ogham, can you upload the fixed version to crates.io or grant me the permission to upload it?

**Comment by MagaTailor** [comment]
The latter is a good idea - I had immediately fixed it for myself but the goal should probably be to have exa compile on ARM for everybody?

-original message-
Subject: Re: [rust-locale] Teh fnial RAM borken carte (#6)
From: Jan Hudec notifications@github.com
Date: 04.02.2016 16:16

@petevine, can you try the latest version from git? It seems this should be fixed by #5.

@ogham, can you upload the fixed version to crates.io or grant me the permission to upload it?

---

**Comment by MagaTailor** [comment]
@jan-hudec 
However, looking at your fix I'm not sure going back to libc 0.1 is the right approach - after all libc 0.2 was partly about catching up to libstd 1.6. So basically, everyone has been upgrading to 0.2 ever since.

Did you test it on `rust 1.5`?

**Comment by ogham** [comment]
I can upload the latest version, but I'm not sure if there's a way for me to grant other people access.

**Comment by ogham** [comment]
locale v0.2 is on crates.io now

**Comment by MagaTailor** [comment]
The same 9 errors are still there in `0.2.0` so there was no code change.

**Comment by ogham** [comment]
Wait, what? I definitely uploaded it.

**Comment by MagaTailor** [comment]
I meant there was no code change relevant to this issue. The crate versioned `0.2.0` is there alright.

**Comment by jan-hudec** [comment]
@petevine, ok, so apparently #5 didn't fix this. What exact target are we talking about (arm-linux-androideabi, arm-unknown-linux-gnueabi or arm-unknown-linux-gnueabihf)?

**Comment by MagaTailor** [comment]
What exactly did you think it was fixing? 

Arm Linux/Android platforms and x86 android are affected.
Either just do the casts for now or we'll soon see how the newly merged `os::std::raw` changes are going to affect this.

**Comment by jan-hudec** [comment]
I don't know what I was fixing. I assumed this is the same error as #5 is, because that's what #5 appears to claim. However, it did not really work. So I'll have to investigate it closer (and kill the pin to libc 0.1, which apparently isn't anything we should want).

**Comment by jan-hudec** [comment]
> Arm Linux/Android platforms and x86 android are affected.

No, they are not. Only `arm-unknown-linux-gnueabi` is.

**Comment by MagaTailor** [comment]
When was android fixed then? (abi is not related, no idea why you keep bringing it up)
If what you're saying is factual you can update the discussion here:

https://github.com/rust-lang/rust/issues/29867

**Comment by jan-hudec** [comment]
Well, @petevine, I am trying to sort out where it actually fails to build. Because I hoped that @sybblow's PR would fix it, but as it apparently does not, I need to know which combinations compile and which don't, so I can actually fix it.

So far I've tried (today's) nightly. I'll test beta and stable too.

**Comment by jan-hudec** [comment]
Ok, from the start, the correct fix should have been to:
- Upgrade to libc 0.2—all the other dependencies of exa did and having a mix of 0.1 and 0.2 makes no sense, especially since the types are correct in 0.2 and _not_ in 0.1
- Put explicit casts in the decode functions that failed. The system returns a pointer and that pointer is to be interpreted as different things and in the failing cases the something is signed char, a.k.a i8, so cast is appropriate there.
- Use definition of `size_t` from `libc` in `locale::linux::ffi`. I don't know why `rust-bindgen` generated what it did, but the C header is using the definition from `stddef.h`, so we should use the `libc` definition (as we then do in `locale::linux`).

This now builds in `arm-unknown-linux-gnueabi` and it builds in `x86_64-unknown-linux-gnu`, `arm-linux-androideabi` and `x86_64-pc-windows-gnu`.

However, I've got a problem with it. With `libc` 0.1, compiling for `x86_64-pc-windows-gnu` and running tests there works fine. With `libc` 0.2, the tests crash under rustc 1.6.0 and 1.7.0-beta.3. They pass under nightly though.

Now the tests fail _before_ entering any of the test-cases, so I believe it is not, actually, our fault. I am not sure how suitable for release it is, though. @ogham, what do you think?

**Comment by ogham** [comment]
If you're compiling for Windows then I'm not even sure how many tests would be run! There are the 'thousands separator' tests, but they don't exactly _test_ anything about the system. Could you please paste the crash that you get?

I'd much rather have libc v0.2 than v0.1 as well.

**Comment by MagaTailor** [comment]
It's wrong to use the explicit `i8` cast on platforms that actually have `u8` - the correct way is to cast to whatever the platform has, using the `_` syntax which will result in a trivial cast. (e.g u8 to u8)

@ogham 
The x86/x86_64 stuff was never affected by this issue so it shouldn't even matter.

**Comment by jan-hudec** [comment]
On Monday 15 of February 2016 08:43:38 petevine wrote:

> When was android fixed then? (abi is not related, no idea why you keep

Actually, as far as locale crate is concerned, the code that failed simply 
isn't compiled on Android (it has the APIs, but not the data to return from 
them), so it couldn't fail there.

## 
- Jan Hudec bulb@ucw.cz

**Comment by jan-hudec** [comment]
On Monday 15 of February 2016 11:47:10 petevine wrote:

> It's wrong to use the explicit `i8` cast on platforms that actually have
> `u8` - the correct way is to cast to whatever the platform has, using the
> `_` syntax which will result in a trivial cast. (e.g u8 to u8)

I am not sure what syntax you mean, but in this case, the function returns a 
`char *`, but depending on the argument it might mean different things and in 
the two cases declared with `i8` where I added the cast it actually means an 
`int8_t *`. So the cast is correct, because it would have been needed in C as 
well. Note that in the cases where the function does mean a string, no cast is 
needed.

**Comment by MagaTailor** [comment]
Instead of `as *const i8` do `as *const _`

The unaffected platforms shouldn't be getting any needless casts.

> Actually, as far as locale crate is concerned, the code that failed simply
> isn't compiled on Android (it has the APIs, but not the data to return from
> them), so it couldn't fail there.

Ok, you meant just this crate . The issue is global - you must have noticed I've been following its fallout for the last 4 months.

**Comment by jan-hudec** [comment]
I pushed 0.2.1, which builds here for arm. It also uses libc 0.2.

**Comment by ogham** [comment]
There has been quite a lot of invisible-to-x86-users ARM breakage.

**Comment by jan-hudec** [comment]
Unfortunately I don't think Travis would have the cross-compilation libraries, not to mention emulator to run the tests. It does have Android emulator, but I am not sure I could get both Android and rust in the same build from it and because Android does not have GNU locales, that would not reveal the problem anyway. And Windows have signed char just as linux.

**Comment by MagaTailor** [comment]
`Rust 1.5` is broken now though. Probably not such a big deal but still, one stable version back should be supported (LFS is only present in 1.8 anyway)

**Comment by jan-hudec** [comment]
On Monday 15 of February 2016 13:32:41 petevine wrote:

> `Rust 1.5` is broken now though. Probably not such a big deal but still, one
> stable version back should be supported.

Everywhere, or just arm?

**Comment by MagaTailor** [comment]
It was fine before cause it was pure libc `0.1` so it's back to the 9 errors. Outta here!

**Comment by jan-hudec** [comment]
On a side-note, I've managed to get `cargo test --target=arm-unknown-linux-gnueabi` to work. There was a couple of hoops to jump through:
- Neither version of multirust supports installing the cross libraries yet, so it has to be done manually as explained [here](https://github.com/japaric/rust-cross).
- Debian/Ubuntu `gcc-multilib` breaks the cross-compilers (except the mingw ones), but `gcc-5-multilib` pulls in everything needed for i386 and x86_64 compilation and does not break anything ([explanation here](https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1300211)). When that's out of the way, just install `g++-arm-linux-gnueabi`.
- `qemu-user-static` package then can directly run ARM binaries as explained [here](https://gist.github.com/bdsatish/7476239), provided key information about configuring is dug out from it's `README.Debian`.

The tests reported one failure; I'll eventually look at it.
